name: Weather Data Scraper

on: 
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download data
        run: weather.sh

      - name: Push data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Fetching the weather"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
